name: Bump Homebrew Cask — oculante

on:
  workflow_dispatch:                      # allow manual trigger
  push:
    tags:
      - '*'

jobs:
  bump-homebrew-cask:
    runs-on: macos-12

    steps:
    - name: Bump Homebrew Cask
      uses: eugenesvk/action-homebrew-bump-cask@3.8.4
      with:
        tap       	: eugenesvk/oculante	# [opt] |homebrew/core|
        cask      	: oculante          	# [req] Cask name
        token     	: ${{secrets.TOKEN}}	# [req] Custom GitHub access token with the 'public_repo'
        # org     	: ORG               	# [opt] Create tap repo fork in organization
        # tag     	: ${{github.ref}}   	# [opt] Determined automatically
        # revision	: ${{github.sha}}   	# [opt] Determined automatically
        # force   	: false             	# [opt] Don't check for already open PR
